routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/clear', function(){
    \Illuminate\Support\Facades\Artisan::call('optimize:clear');
	 \Illuminate\Support\Facades\Artisan::call('view:clear');
});


Route::get('rewards_and_points', function(){
    return view('templates.basic.blog');
});
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get('/cron', 'CronController@cron')->name('bv.matching.cron');
Route::get('/issue_weekly_bonus', 'CronController@issue_weekly_bonus');

Route::namespace('Gateway')->prefix('ipn')->name('ipn.')->group(function () {
    Route::post('paypal', 'Paypal\ProcessController@ipn')->name('Paypal');
    Route::get('paypal-sdk', 'PaypalSdk\ProcessController@ipn')->name('PaypalSdk');
    Route::post('perfect-money', 'PerfectMoney\ProcessController@ipn')->name('PerfectMoney');
    Route::post('stripe', 'Stripe\ProcessController@ipn')->name('Stripe');
    Route::post('stripe-js', 'StripeJs\ProcessController@ipn')->name('StripeJs');
    Route::post('stripe-v3', 'StripeV3\ProcessController@ipn')->name('StripeV3');
    Route::post('skrill', 'Skrill\ProcessController@ipn')->name('Skrill');
    Route::post('paytm', 'Paytm\ProcessController@ipn')->name('Paytm');
    Route::post('payeer', 'Payeer\ProcessController@ipn')->name('Payeer');
    Route::post('paystack', 'Paystack\ProcessController@ipn')->name('Paystack');
    Route::post('voguepay', 'Voguepay\ProcessController@ipn')->name('Voguepay');
    Route::get('flutterwave/{trx}/{type}', 'Flutterwave\ProcessController@ipn')->name('Flutterwave');
    Route::post('razorpay', 'Razorpay\ProcessController@ipn')->name('Razorpay');
    Route::post('instamojo', 'Instamojo\ProcessController@ipn')->name('Instamojo');
    Route::get('blockchain', 'Blockchain\ProcessController@ipn')->name('Blockchain');
    Route::get('blockio', 'Blockio\ProcessController@ipn')->name('Blockio');
    Route::post('coinpayments', 'Coinpayments\ProcessController@ipn')->name('Coinpayments');
    Route::post('coinpayments-fiat', 'Coinpayments_fiat\ProcessController@ipn')->name('CoinpaymentsFiat');
    Route::post('coingate', 'Coingate\ProcessController@ipn')->name('Coingate');
    Route::post('coinbase-commerce', 'CoinbaseCommerce\ProcessController@ipn')->name('CoinbaseCommerce');
    Route::get('mollie', 'Mollie\ProcessController@ipn')->name('Mollie');
    Route::post('cashmaal', 'Cashmaal\ProcessController@ipn')->name('Cashmaal');
    Route::post('authorize-net', 'AuthorizeNet\ProcessController@ipn')->name('AuthorizeNet');
    Route::post('2check-out', 'TwoCheckOut\ProcessController@ipn')->name('TwoCheckOut');
    Route::post('mercado-pago', 'MercadoPago\ProcessController@ipn')->name('MercadoPago');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});

/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('login');
        Route::get('logout', 'LoginController@logout')->name('logout');
        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetCodeEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify.code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset.form');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });

    Route::middleware(['admin'])->group(function () {
        Route::get('clear-company-wallet', 'AdminController@clear_company_wallet')->name('wallet-clear');

        Route::get('dashboard', function(){
           return redirect('/admin/company-dashboard');
        });// 'AdminController@dashboard')->name('dashboard');
        Route::get('summary', 'AdminController@summary')->name('summary');
        Route::get('warehouse-products', 'AdminController@warehouse_products')->name('warehouse.products');
        Route::get('office-statements', 'AdminController@office_statements')->name('office.statements');
        Route::post('summary', 'AdminController@summary')->name('summary');
		
		Route::get('lucky-draw-promos-winners', 'AdminController@lucky_draws')->name('lucky_draws');
		Route::get('lucky-draw-promos-all', 'AdminController@lucky_draw_all')->name('lucky_draw_all');
		Route::post('lucky-draw-promo-winner', 'AdminController@lucky_draw_complete')->name('lucky_draw_complete');
       
        Route::get('company-dashboard', 'AdminController@company_dashboard')->name('dashboard.company');
        Route::get('users-dashboard', 'AdminController@users_dashboard')->name('dashboard.users');
        Route::get('expense-dashboard', 'AdminController@expense_dashboard')->name('dashboard.expense');
       
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');

        //Notification
        Route::get('notifications','AdminController@notifications')->name('notifications');
        Route::get('notification/read/{id}','AdminController@notificationRead')->name('notification.read');
        Route::get('notifications/read-all','AdminController@readAll')->name('notifications.readAll');

        // mlm plan
        Route::get('plans', 'MlmController@plan')->name('plan');
        Route::post('plan/store', 'MlmController@planStore')->name('plan.store');
        Route::post('plan/update', 'MlmController@planUpdate')->name('plan.update');
		
		//rewards management
		Route::get('rewards-users', 'AdminController@reward_users')->name('reward-users');
        Route::post('deliver-reward', 'AdminController@deliver_reward')->name('deliver-reward');

        // mlm stockist
        //Route::get('stockists', 'MlmController@stockist')->name('stockist');
        //Route::post('stockist/store', 'MlmController@stockistStore')->name('stockist.store');
        //Route::post('stockist/update', 'MlmController@stockistUpdate')->name('stockist.update');

        // matching bonus
        Route::post('matching-bonus/update', 'MlmController@matchingUpdate')->name('matching-bonus.update');

        // tree
        Route::get('/tree/{id}', 'ManageUsersController@tree')->name('users.single.tree');
        Route::get('/user/tree/{user}', 'ManageUsersController@otherTree')->name('users.other.tree');
        Route::get('/user/tree/search', 'ManageUsersController@otherTree')->name('users.other.tree.search');

        Route::get('notice', 'GeneralSettingController@noticeIndex')->name('setting.notice');
        Route::post('notice/update', 'GeneralSettingController@noticeUpdate')->name('setting.notice.update');

		//============== start the Pin ===========
        Route::get('stockists','MlmController@stockists')->name('stockists');
        Route::post('stockist/store', 'MlmController@stockistStore')->name('stockist.store');
        Route::post('stockist/update', 'MlmController@stockistUpdate')->name('stockist.update');
        Route::get('stockist/list', 'MlmController@stockistList')->name('stockist.list');
		
		//============== start the membership ===========

        Route::get('memberShip','MlmController@memberShip')->name('memberShip');
        Route::post('memberShip_Store','MlmController@memberShip_Store')->name('membership.store');
        Route::post('memberShip_update','MlmController@memberShip_update')->name('membership.update');

        //============== start the category route ===========
        Route::name('category.')->prefix('category')->group(function () {
            Route::get('/', 'CategoryController@index')->name('index');
            Route::post('/store', 'CategoryController@store')->name('store');
            Route::post('/update/{id}', 'CategoryController@update')->name('update');
            Route::get('/status/change/{id}', 'CategoryController@changeStatus')->name('status.change');
        });

         //============== start the product route ===========
         Route::name('product.')->prefix('product')->group(function () {
            Route::get('/', 'ProductController@index')->name('index');
            Route::get('/create', 'ProductController@create')->name('create');
            Route::post('/store', 'ProductController@store')->name('store');
            Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
            Route::post('/update/{id}', 'ProductController@update')->name('update');
            Route::get('/status/change/{id}', 'ProductController@changeStatus')->name('status.change');
            Route::get('remove-image/{id}/{key}', 'ProductController@removeImage')->name('image.remove');
        });


        //Report Bugs
        Route::get('request-report','AdminController@requestReport')->name('request.report');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'address' => 'object',
        'ver_code_send_at' => 'datetime'
    ];

    protected $data = [
        'data'=>1
    ];




    public function login_logs()
    {
        return $this->hasMany(UserLogin::class);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class)->orderBy('id','desc');
    }

    public function deposits()
    {
        return $this->hasMany(Deposit::class)->where('status','!=',0);
    }

    public function withdrawals()
    {
        return $this->hasMany(Withdrawal::class)->where('status','!=',0);
    }

    //mlm
    public function userExtra()
    {
        return $this->hasOne(UserExtra::class);
    }

    public function plan()
    {
        return $this->belongsTo(Plan::class);
    }


    // SCOPES

    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function scopeActive()
    {
        return $this->where('status', 1);
    }

    public function scopeBanned()
    {
        return $this->where('status', 0);
    }

    public function scopeEmailUnverified()
    {
        return $this->where('ev', 0);
    }

    public function scopeSmsUnverified()
    {
        return $this->where('sv', 0);
    }
    public function scopeEmailVerified()
    {
        return $this->where('ev', 1);
    }

    public function scopeSmsVerified()
    {
        return $this->where('sv', 1);
    }

}

resources/views/admin/calculator.blade.php
@extends('admin.layouts.app')

@section('panel')


   
   <div>
  <label for="upline-users">Number of users in upline:</label>
  <input type="number" id="upline-users" name="upline-users">
</div>

<div>
  <label for="downline-users">Number of users in downline:</label>
  <input type="number" id="downline-users" name="downline-users">
</div>

<button onclick="calculatePairs()">Calculate</button>

<p id="result"></p>


@endsection




@push('script')
    <script>
		function calculatePairs() {
  const uplineUsers = parseInt(document.getElementById("upline-users").value);
  const downlineUsers = parseInt(document.getElementById("downline-users").value);

  // Calculate pairs in upline
  let uplinePairs = 0;
  for (let i = 1; i <= 11; i++) {
    const levelUsers = Math.pow(2, i-1);
    const levelPairs = levelUsers * (i-1);
    uplinePairs += levelPairs;
  }

  // Calculate pairs in downline
  let downlinePairs = 0;
  for (let i = 1; i <= 11; i++) {
    const levelUsers = Math.pow(2, i-1);
    const levelPairs = levelUsers * (i-1);
    downlinePairs += levelPairs * (downlineUsers - uplineUsers);
  }

  const totalPairs = uplinePairs + downlinePairs;

  const result = `The total number of pairs in the upline and downline would be ${totalPairs.toLocaleString()} pairs. (Upline: ${uplinePairs.toLocaleString()} pairs, Downline: ${downlinePairs.toLocaleString()} pairs)`;

  document.getElementById("result").innerText = result;
}

    </script>

@endpush

resources/views/admin/lucky_draw_all.blade.php
@extends('admin.layouts.app')

@section('panel')
<style>

    @media (max-width: 767px) {

        table.style--two tbody tr {

            border: 2px dashed #0000005c;

            display: block;

            margin-bottom: 20px;

            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);

            transition: box-shadow 0.3s ease-in-out;

        }

        table.style--two tbody tr:hover {

            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.4);

            transition: box-shadow 0.3s ease-in-out;

        }

    }

</style>


    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body p-0">
                    <div class="table-responsive--md table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Sl')</th>
                                <th scope="col">@lang('Username')</th>
                                <th scope="col">@lang('LDP')</th>
                             
                                <th scope="col">@lang('Full Name')</th>
                                <th scope="col">@lang('City')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php $reversedLuckyDrawAll = $lucky_draw_all->reverse(); @endphp

@forelse($reversedLuckyDrawAll as $key => $promo)
    <tr>
        <td data-label="@lang('Sl')">{{$key+1}}</td>
        <td data-label="@lang('Username')">{{ __($promo->username) }}</td>
        <td data-label="@lang('LDP')">{{ __($promo->dlp) }}</td>
        <?php $user = \App\Models\User::where('username', $promo->username)->first(); ?>
        <td data-label="@lang('Full Name')">{{$user->firstname}} {{$user->lastname }}</td>
        <td data-label="@lang('City')">{{$user->address->city}}</td>
    </tr>
@empty
    <tr>
        <td class="text-muted text-center" colspan="100%">{{ __($emptyMessage) }}</td>
    </tr>
@endforelse


                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{ $lucky_draw_all->links('admin.partials.paginate') }}
                </div>
            </div>
        </div>
    </div>



    <div id="edit-plan" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@lang('Complete Lucky Draw PROMO')</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" action="{{route('admin.lucky_draw_complete')}}">
                    @csrf
                    <div class="modal-body">

                        <input class="form-control plan_id" type="hidden" name="id">

                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label class="font-weight-bold"> @lang('Username') :</label>
                                <input class="form-control name" name="name" required>
                            </div>
                   
                        </div>


                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-block btn--primary">@lang('Complete')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    

@endsection
@push('breadcrumb-plugins')

    <form action="{{ route('admin.lucky_draw_all')}}" method="GET" class="form-inline float-sm-right bg--white"><div class="col-12 col-md-6">
		
		<div class="input-group">

            <input type="text" name="city" class="form-control" placeholder="@lang('City')" value="{{ $search ?? '' }}">

        </div></div><div class="col-12 col-md-6">

		

	

	<div class="input-group has_append">

            <input type="text" name="search" class="form-control" placeholder="@lang(' Username')" value="{{ $search ?? '' }}">

            <div class="input-group-append">

                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>

            </div>

        </div></div>

    </form>

@endpush



@push('script')
    <script>
        "use strict";
        (function ($) {
            $('.edit').on('click', function () {
                var modal = $('#edit-plan');
              
                modal.find('.name').val($(this).data('name'));
                modal.find('.type').val($(this).data('type'));
                modal.find('.price').val($(this).data('price'));
                if($(this).data('status')){
                    modal.find('.toggle').removeClass('btn--danger off').addClass('btn--success');
                    modal.find('input[name="status"]').prop('checked',true);

                }else{
                    modal.find('.toggle').addClass('btn--danger off').removeClass('btn--success');
                    modal.find('input[name="status"]').prop('checked',false);
                }

                modal.find('input[name=id]').val($(this).data('id'));
                modal.modal('show');
            });

            $('.add-plan').on('click', function () {
                var modal = $('#add-plan');
                modal.modal('show');
            });
        })(jQuery);
    </script>
@endpush

resources/views/admin/lucky_draw_promos.blade.php
@extends('admin.layouts.app')

@section('panel')
        <div class="col-xl-3 col-lg-4 col-sm-6 mb-30">
            <div class="dashboard-w1 bg--primary b-radius--10 box-shadow">
                <div class="icon">
                    <i class="fa fa-users"></i>
                </div>
                <div class="details">
                    <div class="numbers">
                        <span class="amount">Total DLP: {{ $dlps }} </span>

                    </div>
                    <div class="desciption">
                        <span class="text--small">@lang('Current DLP '): @if($dlp){{$dlp->dlp}}@endif</span>
                    </div>
  					<div class="desciption">
                        <a href="{{ route('admin.lucky_draw_all') }}"
                            class="btn btn-sm text--small bg--white text--black box--shadow3 mt3">
                            @lang('View All')
                        </a>
                    </div>
                </div>
            </div>
        </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body p-0">
                    <div class="table-responsive--md table-responsive">
                        <table class="table table--light style--two">
                            <thead>
                            <tr>
                                <th scope="col">@lang('Sl')</th>
                                <th scope="col">@lang('Username')</th>
                                <th scope="col">@lang('PROMO Name')</th>
                             
                                <th scope="col">@lang('Status')</th>
                                <th scope="col">@lang('Action')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($lucky_draw_promos as $key => $promo)
                                <tr>
                                    <td data-label="@lang('Sl')">{{$key+1}}</td>
                                    <td data-label="@lang('Name')">{{ __($promo->username) }}</td>
                                    <td data-label="@lang('Name')">{{ __($promo->promo) }}</td>
                                    <td data-label="@lang('Status')">
                                        @if($promo->status == 1)
                                            <span class="text--small badge font-weight-normal badge--success">@lang('Completed')</span>
                                        @else
                                            <span class="text--small badge font-weight-normal badge--danger">@lang('Pending')</span>
                                        @endif
                                    </td>
									 <td data-label="@lang('Action')">
                                        <button type="button" class="icon-btn edit" data-toggle="tooltip"
                                                data-id="{{ $promo->id }}"
                                                data-name="{{ $promo->username }}"
                                                
                                                data-original-title="Complete">
                                            <i class="la la-pencil"></i>
                                        </button>
                                    </td>
                                
                                </tr>
                            @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ __($emptyMessage) }}</td>
                                </tr>
                            @endforelse

                            </tbody>
                        </table><!-- table end -->
                    </div>
                </div>
                <div class="card-footer py-4">
                    {{ $lucky_draw_promos->links('admin.partials.paginate') }}
                </div>
            </div>
        </div>
    </div>



    <div id="edit-plan" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@lang('Complete Lucky Draw PROMO')</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" action="{{route('admin.lucky_draw_complete')}}">
                    @csrf
                    <div class="modal-body">

                        <input class="form-control plan_id" type="hidden" name="id">

                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label class="font-weight-bold"> @lang('Username') :</label>
                                <input class="form-control name" name="name" required>
                            </div>
                   
                        </div>


                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-block btn--primary">@lang('Complete')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    

@endsection




@push('script')
    <script>
        "use strict";
        (function ($) {
            $('.edit').on('click', function () {
                var modal = $('#edit-plan');
              
                modal.find('.name').val($(this).data('name'));
                modal.find('.type').val($(this).data('type'));
                modal.find('.price').val($(this).data('price'));
                if($(this).data('status')){
                    modal.find('.toggle').removeClass('btn--danger off').addClass('btn--success');
                    modal.find('input[name="status"]').prop('checked',true);

                }else{
                    modal.find('.toggle').addClass('btn--danger off').removeClass('btn--success');
                    modal.find('input[name="status"]').prop('checked',false);
                }

                modal.find('input[name=id]').val($(this).data('id'));
                modal.modal('show');
            });

            $('.add-plan').on('click', function () {
                var modal = $('#add-plan');
                modal.modal('show');
            });
        })(jQuery);
    </script>
@endpush

resources/views/admin/notice.blade.php
@extends('admin.layouts.app')

@section('panel')
    <div class="col-lg-12">
        <div class="card">
            <form action="{{ route('admin.setting.notice.update') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>@lang('All user notice')</label>
                                <textarea rows="10" class="form-control nicEdit"  name="notice">{{ __($general->notice) }}</textarea>
                            </div>
                            <div class="form-group">
                                <label>@lang('Free user notice')</label>
                                <textarea rows="10" class="form-control nicEdit"  name="free_user_notice">{{ __($general->free_user_notice) }}</textarea>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="card-footer py-4">
                    <button type="submit" class="btn btn-block btn--primary mr-2">@lang('Update')</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/password.blade.php
@extends('admin.layouts.app')

@section('panel')
    <div class="row mb-none-30">
        <div class="col-lg-3 col-md-3 mb-30">

            <div class="card b-radius--5 overflow-hidden">
                <div class="card-body p-0">
                    <div class="d-flex p-3 bg--primary">
                        <div class="avatar avatar--lg">
                            <img src="{{ getImage(imagePath()['profile']['admin']['path'].'/'. $admin->image,imagePath()['profile']['admin']['size'])}}" alt="@lang('Image')">
                        </div>
                        <div class="pl-3">
                            <h4 class="text--white">{{__($admin->name)}}</h4>
                        </div>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Name')
                            <span class="font-weight-bold">{{ __($admin->name) }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Username')
                            <span  class="font-weight-bold">{{ __($admin->username) }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Email')
                            <span  class="font-weight-bold">{{ $admin->email }}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-lg-9 col-md-9 mb-30">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title mb-50 border-bottom pb-2">@lang('Change Password')</h5>

                    <form action="{{ route('admin.password.update') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label  ">@lang('Password')</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="password" placeholder="@lang('Password')" name="old_password">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label  ">@lang('New Password')</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="password" placeholder="@lang('New Password')" name="password">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label  ">@lang('Confirm Password')</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="password" placeholder="@lang('Confirm Password')" name="password_confirmation">
                            </div>
                        </div>


                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label  "></label>
                            <div class="col-lg-9">
                            <button type="submit" class="btn btn--primary btn-block btn-lg">@lang('Save Changes')</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('breadcrumb-plugins')
    <a href="{{route('admin.profile')}}" class="btn btn-sm btn--primary box--shadow1 text--small" ><i class="fa fa-user"></i>@lang('Profile Setting')</a>
@endpush